"""
Braille art helper for the profile SVGs.

The ascii block in dark_mode.svg / light_mode.svg is an image rendered into Unicode braille,
where each character is a 2-wide x 4-tall grid of dots. This module converts that block back
to a bitmap and forward again, so the art can be edited as pixels instead of by hand.

    python tools/braille.py                     # run the self-check
    python tools/braille.py --dump art.png      # decode the SVG art to a PNG
    python tools/braille.py --inject art.png    # encode a PNG back into both SVGs

Not used by the daily workflow: the art is regenerated by hand and committed, which keeps
Pillow out of the job that holds the API token.
"""
import re
import sys

BLANK = '⠀'
# Bit weight of each (x, y) dot inside a 2x4 cell. Dots 7 and 8 are the bottom row, which is
# why the last two weights are out of reading order.
DOT_BITS = {(0, 0): 0x01, (0, 1): 0x02, (0, 2): 0x04,
            (1, 0): 0x08, (1, 1): 0x10, (1, 2): 0x20,
            (0, 3): 0x40, (1, 3): 0x80}

ART_BLOCK = re.compile(r'(<text[^>]*class="ascii"[^>]*>)(.*?)(</text>)', re.S)
TSPAN = re.compile(r'<tspan[^>]*>(.*?)</tspan>', re.S)


def read_art(svg_path):
    """Returns the braille art in an SVG as a list of equal-length strings."""
    with open(svg_path, encoding='utf-8') as f:
        block = ART_BLOCK.search(f.read())
    rows = [row.replace(' ', BLANK) for row in TSPAN.findall(block.group(2))]
    width = max(len(row) for row in rows)
    return [row.ljust(width, BLANK) for row in rows]


def to_bitmap(rows):
    """Braille rows -> a 1-bit Pillow image, one pixel per dot. Set dots are black."""
    from PIL import Image
    image = Image.new('1', (len(rows[0]) * 2, len(rows) * 4), 1)
    pixels = image.load()
    for row_index, row in enumerate(rows):
        for col_index, char in enumerate(row):
            mask = ord(char) - 0x2800
            for (dot_x, dot_y), bit in DOT_BITS.items():
                if mask & bit:
                    pixels[col_index * 2 + dot_x, row_index * 4 + dot_y] = 0
    return image


def to_braille(image):
    """A 1-bit Pillow image -> braille rows. Dark pixels become set dots."""
    pixels = image.convert('1').load()
    width, height = image.size
    rows = []
    for top in range(0, height, 4):
        row = ''
        for left in range(0, width, 2):
            mask = 0
            for (dot_x, dot_y), bit in DOT_BITS.items():
                x, y = left + dot_x, top + dot_y
                if x < width and y < height and pixels[x, y] == 0:
                    mask |= bit
            row += chr(0x2800 + mask)
        rows.append(row)
    return rows


def write_art(svg_path, rows, x=15, y=22, line_height=15, text_length=440):
    """
    Replaces the braille art in an SVG, leaving every other element alone.

    textLength pins each row to an exact width. Braille is usually missing from Consolas, so
    the browser substitutes some other font whose advance we cannot predict - without this the
    art would be free to grow past its column and collide with the stats block beside it.
    """
    with open(svg_path, encoding='utf-8') as f:
        svg = f.read()
    tspans = '\n' + '\n'.join(
        f'<tspan x="{x}" y="{y + index * line_height}" '
        f'textLength="{text_length}" lengthAdjust="spacingAndGlyphs">{row}</tspan>'
        for index, row in enumerate(rows)) + '\n'
    with open(svg_path, 'w', encoding='utf-8') as f:
        f.write(ART_BLOCK.sub(lambda m: m.group(1) + tspans + m.group(3), svg, count=1))


def self_check():
    # Dots 1 and 8, i.e. top-left and bottom-right, is U+2881 by definition.
    assert to_braille(_pattern({(0, 0), (1, 3)})) == ['⢁']
    # A full cell is U+28FF, an empty one U+2800.
    assert to_braille(_pattern(set(DOT_BITS))) == ['⣿']
    assert to_braille(_pattern(set())) == [BLANK]
    # Decoding and re-encoding has to be lossless, or editing the art would corrupt it.
    for rows in (['⠁⣿⠀'], ['⡇⠒', '⢠⠀']):
        assert to_braille(to_bitmap(rows)) == rows, rows
    print('braille self-check passed')


def _pattern(dots):
    from PIL import Image
    image = Image.new('1', (2, 4), 1)
    for dot in dots:
        image.load()[dot] = 0
    return image


if __name__ == '__main__':
    if '--dump' in sys.argv:
        to_bitmap(read_art('dark_mode.svg')).save(sys.argv[sys.argv.index('--dump') + 1])
    elif '--inject' in sys.argv:
        from PIL import Image
        rows = to_braille(Image.open(sys.argv[sys.argv.index('--inject') + 1]))
        for svg in ('dark_mode.svg', 'light_mode.svg'):
            write_art(svg, rows)
        print(f'wrote {len(rows)} rows x {len(rows[0])} cols into both SVGs')
    else:
        self_check()
