name: README build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

# Add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to v3
        with:
          fetch-depth: 1
      - name: Create cache directory
        run: mkdir -p cache
      - name: Set up Python
        uses: actions/setup-python@v4  # Update to v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dateutil requests lxml
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python today.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
